exports.ePub = require('../lib/epub.legacy.js')
exports.xmldom = require('../lib/xmldom/lib/dom-parser.js')
exports.path = require('../lib/path.js')
exports.mime = require('../lib/mime.min.js')
exports.base64 = require('../lib/base64-js/index.js')
